<?php namespace App\Database\Seeds;

class PaisesSeeder extends \CodeIgniter\Database\Seeder
{
        public function run()
        {
                $paises = [
                        ['codigo' => 'US', 'nombre' => 'United States'],
                        ['codigo' => 'CA', 'nombre' => 'Canada'],
                        ['codigo' => 'AF', 'nombre' => 'Afghanistan'],
                        ['codigo' => 'AL', 'nombre' => 'Albania'],
                        ['codigo' => 'DZ', 'nombre' => 'Algeria'],
                        ['codigo' => 'AS', 'nombre' => 'American Samoa'],
                        ['codigo' => 'AD', 'nombre' => 'Andorra'],
                        ['codigo' => 'AO', 'nombre' => 'Angola'],
                        ['codigo' => 'AI', 'nombre' => 'Anguilla'],
                        ['codigo' => 'AQ', 'nombre' => 'Antarctica'],
                        ['codigo' => 'AG', 'nombre' => 'Antigua and/or Barbuda'],
                        ['codigo' => 'AR', 'nombre' => 'Argentina'],
                        ['codigo' => 'AM', 'nombre' => 'Armenia'],
                        ['codigo' => 'AW', 'nombre' => 'Aruba'],
                        ['codigo' => 'AU', 'nombre' => 'Australia'],
                        ['codigo' => 'AT', 'nombre' => 'Austria'],
                        ['codigo' => 'AZ', 'nombre' => 'Azerbaijan'],
                        ['codigo' => 'BS', 'nombre' => 'Bahamas'],
                        ['codigo' => 'BH', 'nombre' => 'Bahrain'],
                        ['codigo' => 'BD', 'nombre' => 'Bangladesh'],
                        ['codigo' => 'BB', 'nombre' => 'Barbados'],
                        ['codigo' => 'BY', 'nombre' => 'Belarus'],
                        ['codigo' => 'BE', 'nombre' => 'Belgium'],
                        ['codigo' => 'BZ', 'nombre' => 'Belize'],
                        ['codigo' => 'BJ', 'nombre' => 'Benin'],
                        ['codigo' => 'BM', 'nombre' => 'Bermuda'],
                        ['codigo' => 'BT', 'nombre' => 'Bhutan'],
                        ['codigo' => 'BO', 'nombre' => 'Bolivia'],
                        ['codigo' => 'BA', 'nombre' => 'Bosnia and Herzegovina'],
                        ['codigo' => 'BW', 'nombre' => 'Botswana'],
                        ['codigo' => 'BV', 'nombre' => 'Bouvet Island'],
                        ['codigo' => 'BR', 'nombre' => 'Brazil'],
                        ['codigo' => 'IO', 'nombre' => 'British lndian Ocean Territory'],
                        ['codigo' => 'BN', 'nombre' => 'Brunei Darussalam'],
                        ['codigo' => 'BG', 'nombre' => 'Bulgaria'],
                        ['codigo' => 'BF', 'nombre' => 'Burkina Faso'],
                        ['codigo' => 'BI', 'nombre' => 'Burundi'],
                        ['codigo' => 'KH', 'nombre' => 'Cambodia'],
                        ['codigo' => 'CM', 'nombre' => 'Cameroon'],
                        ['codigo' => 'CV', 'nombre' => 'Cape Verde'],
                        ['codigo' => 'KY', 'nombre' => 'Cayman Islands'],
                        ['codigo' => 'CF', 'nombre' => 'Central African Republic'],
                        ['codigo' => 'TD', 'nombre' => 'Chad'],
                        ['codigo' => 'CL', 'nombre' => 'Chile'],
                        ['codigo' => 'CN', 'nombre' => 'China'],
                        ['codigo' => 'CX', 'nombre' => 'Christmas Island'],
                        ['codigo' => 'CC', 'nombre' => 'Cocos (Keeling) Islands'],
                        ['codigo' => 'CO', 'nombre' => 'Colombia'],
                        ['codigo' => 'KM', 'nombre' => 'Comoros'],
                        ['codigo' => 'CG', 'nombre' => 'Congo'],
                        ['codigo' => 'CK', 'nombre' => 'Cook Islands'],
                        ['codigo' => 'CR', 'nombre' => 'Costa Rica'],
                        ['codigo' => 'HR', 'nombre' => 'Croatia (Hrvatska)'],
                        ['codigo' => 'CU', 'nombre' => 'Cuba'],
                        ['codigo' => 'CY', 'nombre' => 'Cyprus'],
                        ['codigo' => 'CZ', 'nombre' => 'Czech Republic'],
                        ['codigo' => 'CD', 'nombre' => 'Democratic Republic of Congo'],
                        ['codigo' => 'DK', 'nombre' => 'Denmark'],
                        ['codigo' => 'DJ', 'nombre' => 'Djibouti'],
                        ['codigo' => 'DM', 'nombre' => 'Dominica'],
                        ['codigo' => 'DO', 'nombre' => 'Dominican Republic'],
                        ['codigo' => 'TP', 'nombre' => 'East Timor'],
                        ['codigo' => 'EC', 'nombre' => 'Ecudaor'],
                        ['codigo' => 'EG', 'nombre' => 'Egypt'],
                        ['codigo' => 'SV', 'nombre' => 'El Salvador'],
                        ['codigo' => 'GQ', 'nombre' => 'Equatorial Guinea'],
                        ['codigo' => 'ER', 'nombre' => 'Eritrea'],
                        ['codigo' => 'EE', 'nombre' => 'Estonia'],
                        ['codigo' => 'ET', 'nombre' => 'Ethiopia'],
                        ['codigo' => 'FK', 'nombre' => 'Falkland Islands (Malvinas)'],
                        ['codigo' => 'FO', 'nombre' => 'Faroe Islands'],
                        ['codigo' => 'FJ', 'nombre' => 'Fiji'],
                        ['codigo' => 'FI', 'nombre' => 'Finland'],
                        ['codigo' => 'FR', 'nombre' => 'France'],
                        ['codigo' => 'FX', 'nombre' => 'France, Metropolitan'],
                        ['codigo' => 'GF', 'nombre' => 'French Guiana'],
                        ['codigo' => 'PF', 'nombre' => 'French Polynesia'],
                        ['codigo' => 'TF', 'nombre' => 'French Southern Territories'],
                        ['codigo' => 'GA', 'nombre' => 'Gabon'],
                        ['codigo' => 'GM', 'nombre' => 'Gambia'],
                        ['codigo' => 'GE', 'nombre' => 'Georgia'],
                        ['codigo' => 'DE', 'nombre' => 'Germany'],
                        ['codigo' => 'GH', 'nombre' => 'Ghana'],
                        ['codigo' => 'GI', 'nombre' => 'Gibraltar'],
                        ['codigo' => 'GR', 'nombre' => 'Greece'],
                        ['codigo' => 'GL', 'nombre' => 'Greenland'],
                        ['codigo' => 'GD', 'nombre' => 'Grenada'],
                        ['codigo' => 'GP', 'nombre' => 'Guadeloupe'],
                        ['codigo' => 'GU', 'nombre' => 'Guam'],
                        ['codigo' => 'GT', 'nombre' => 'Guatemala'],
                        ['codigo' => 'GN', 'nombre' => 'Guinea'],
                        ['codigo' => 'GW', 'nombre' => 'Guinea-Bissau'],
                        ['codigo' => 'GY', 'nombre' => 'Guyana'],
                        ['codigo' => 'HT', 'nombre' => 'Haiti'],
                        ['codigo' => 'HM', 'nombre' => 'Heard and Mc Donald Islands'],
                        ['codigo' => 'HN', 'nombre' => 'Honduras'],
                        ['codigo' => 'HK', 'nombre' => 'Hong Kong'],
                        ['codigo' => 'HU', 'nombre' => 'Hungary'],
                        ['codigo' => 'IS', 'nombre' => 'Iceland'],
                        ['codigo' => 'IN', 'nombre' => 'India'],
                        ['codigo' => 'ID', 'nombre' => 'Indonesia'],
                        ['codigo' => 'IR', 'nombre' => 'Iran (Islamic Republic of)'],
                        ['codigo' => 'IQ', 'nombre' => 'Iraq'],
                        ['codigo' => 'IE', 'nombre' => 'Ireland'],
                        ['codigo' => 'IL', 'nombre' => 'Israel'],
                        ['codigo' => 'IT', 'nombre' => 'Italy'],
                        ['codigo' => 'CI', 'nombre' => 'Ivory Coast'],
                        ['codigo' => 'JM', 'nombre' => 'Jamaica'],
                        ['codigo' => 'JP', 'nombre' => 'Japan'],
                        ['codigo' => 'JO', 'nombre' => 'Jordan'],
                        ['codigo' => 'KZ', 'nombre' => 'Kazakhstan'],
                        ['codigo' => 'KE', 'nombre' => 'Kenya'],
                        ['codigo' => 'KI', 'nombre' => 'Kiribati'],
                        ['codigo' => 'KP', 'nombre' => 'Korea, Democratic People\'s Republic of'],
                        ['codigo' => 'KR', 'nombre' => 'Korea, Republic of'],
                        ['codigo' => 'KW', 'nombre' => 'Kuwait'],
                        ['codigo' => 'KG', 'nombre' => 'Kyrgyzstan'],
                        ['codigo' => 'LA', 'nombre' => 'Lao People\'s Democratic Republic'],
                        ['codigo' => 'LV', 'nombre' => 'Latvia'],
                        ['codigo' => 'LB', 'nombre' => 'Lebanon'],
                        ['codigo' => 'LS', 'nombre' => 'Lesotho'],
                        ['codigo' => 'LR', 'nombre' => 'Liberia'],
                        ['codigo' => 'LY', 'nombre' => 'Libyan Arab Jamahiriya'],
                        ['codigo' => 'LI', 'nombre' => 'Liechtenstein'],
                        ['codigo' => 'LT', 'nombre' => 'Lithuania'],
                        ['codigo' => 'LU', 'nombre' => 'Luxembourg'],
                        ['codigo' => 'MO', 'nombre' => 'Macau'],
                        ['codigo' => 'MK', 'nombre' => 'Macedonia'],
                        ['codigo' => 'MG', 'nombre' => 'Madagascar'],
                        ['codigo' => 'MW', 'nombre' => 'Malawi'],
                        ['codigo' => 'MY', 'nombre' => 'Malaysia'],
                        ['codigo' => 'MV', 'nombre' => 'Maldives'],
                        ['codigo' => 'ML', 'nombre' => 'Mali'],
                        ['codigo' => 'MT', 'nombre' => 'Malta'],
                        ['codigo' => 'MH', 'nombre' => 'Marshall Islands'],
                        ['codigo' => 'MQ', 'nombre' => 'Martinique'],
                        ['codigo' => 'MR', 'nombre' => 'Mauritania'],
                        ['codigo' => 'MU', 'nombre' => 'Mauritius'],
                        ['codigo' => 'TY', 'nombre' => 'Mayotte'],
                        ['codigo' => 'MX', 'nombre' => 'Mexico'],
                        ['codigo' => 'FM', 'nombre' => 'Micronesia, Federated States of'],
                        ['codigo' => 'MD', 'nombre' => 'Moldova, Republic of'],
                        ['codigo' => 'MC', 'nombre' => 'Monaco'],
                        ['codigo' => 'MN', 'nombre' => 'Mongolia'],
                        ['codigo' => 'MS', 'nombre' => 'Montserrat'],
                        ['codigo' => 'MA', 'nombre' => 'Morocco'],
                        ['codigo' => 'MZ', 'nombre' => 'Mozambique'],
                        ['codigo' => 'MM', 'nombre' => 'Myanmar'],
                        ['codigo' => 'NA', 'nombre' => 'Namibia'],
                        ['codigo' => 'NR', 'nombre' => 'Nauru'],
                        ['codigo' => 'NP', 'nombre' => 'Nepal'],
                        ['codigo' => 'NL', 'nombre' => 'Netherlands'],
                        ['codigo' => 'AN', 'nombre' => 'Netherlands Antilles'],
                        ['codigo' => 'NC', 'nombre' => 'New Caledonia'],
                        ['codigo' => 'NZ', 'nombre' => 'New Zealand'],
                        ['codigo' => 'NI', 'nombre' => 'Nicaragua'],
                        ['codigo' => 'NE', 'nombre' => 'Niger'],
                        ['codigo' => 'NG', 'nombre' => 'Nigeria'],
                        ['codigo' => 'NU', 'nombre' => 'Niue'],
                        ['codigo' => 'NF', 'nombre' => 'Norfork Island'],
                        ['codigo' => 'MP', 'nombre' => 'Northern Mariana Islands'],
                        ['codigo' => 'NO', 'nombre' => 'Norway'],
                        ['codigo' => 'OM', 'nombre' => 'Oman'],
                        ['codigo' => 'PK', 'nombre' => 'Pakistan'],
                        ['codigo' => 'PW', 'nombre' => 'Palau'],
                        ['codigo' => 'PA', 'nombre' => 'Panama'],
                        ['codigo' => 'PG', 'nombre' => 'Papua New Guinea'],
                        ['codigo' => 'PY', 'nombre' => 'Paraguay'],
                        ['codigo' => 'PE', 'nombre' => 'Peru'],
                        ['codigo' => 'PH', 'nombre' => 'Philippines'],
                        ['codigo' => 'PN', 'nombre' => 'Pitcairn'],
                        ['codigo' => 'PL', 'nombre' => 'Poland'],
                        ['codigo' => 'PT', 'nombre' => 'Portugal'],
                        ['codigo' => 'PR', 'nombre' => 'Puerto Rico'],
                        ['codigo' => 'QA', 'nombre' => 'Qatar'],
                        ['codigo' => 'SS', 'nombre' => 'Republic of South Sudan'],
                        ['codigo' => 'RE', 'nombre' => 'Reunion'],
                        ['codigo' => 'RO', 'nombre' => 'Romania'],
                        ['codigo' => 'RU', 'nombre' => 'Russian Federation'],
                        ['codigo' => 'RW', 'nombre' => 'Rwanda'],
                        ['codigo' => 'KN', 'nombre' => 'Saint Kitts and Nevis'],
                        ['codigo' => 'LC', 'nombre' => 'Saint Lucia'],
                        ['codigo' => 'VC', 'nombre' => 'Saint Vincent and the Grenadines'],
                        ['codigo' => 'WS', 'nombre' => 'Samoa'],
                        ['codigo' => 'SM', 'nombre' => 'San Marino'],
                        ['codigo' => 'ST', 'nombre' => 'Sao Tome and Principe'],
                        ['codigo' => 'SA', 'nombre' => 'Saudi Arabia'],
                        ['codigo' => 'SN', 'nombre' => 'Senegal'],
                        ['codigo' => 'RS', 'nombre' => 'Serbia'],
                        ['codigo' => 'SC', 'nombre' => 'Seychelles'],
                        ['codigo' => 'SL', 'nombre' => 'Sierra Leone'],
                        ['codigo' => 'SG', 'nombre' => 'Singapore'],
                        ['codigo' => 'SK', 'nombre' => 'Slovakia'],
                        ['codigo' => 'SI', 'nombre' => 'Slovenia'],
                        ['codigo' => 'SB', 'nombre' => 'Solomon Islands'],
                        ['codigo' => 'SO', 'nombre' => 'Somalia'],
                        ['codigo' => 'ZA', 'nombre' => 'South Africa'],
                        ['codigo' => 'GS', 'nombre' => 'South Georgia South Sandwich Islands'],
                        ['codigo' => 'ES', 'nombre' => 'Spain'],
                        ['codigo' => 'LK', 'nombre' => 'Sri Lanka'],
                        ['codigo' => 'SH', 'nombre' => 'St. Helena'],
                        ['codigo' => 'PM', 'nombre' => 'St. Pierre and Miquelon'],
                        ['codigo' => 'SD', 'nombre' => 'Sudan'],
                        ['codigo' => 'SR', 'nombre' => 'Suriname'],
                        ['codigo' => 'SJ', 'nombre' => 'Svalbarn and Jan Mayen Islands'],
                        ['codigo' => 'SZ', 'nombre' => 'Swaziland'],
                        ['codigo' => 'SE', 'nombre' => 'Sweden'],
                        ['codigo' => 'CH', 'nombre' => 'Switzerland'],
                        ['codigo' => 'SY', 'nombre' => 'Syrian Arab Republic'],
                        ['codigo' => 'TW', 'nombre' => 'Taiwan'],
                        ['codigo' => 'TJ', 'nombre' => 'Tajikistan'],
                        ['codigo' => 'TZ', 'nombre' => 'Tanzania, United Republic of'],
                        ['codigo' => 'TH', 'nombre' => 'Thailand'],
                        ['codigo' => 'TG', 'nombre' => 'Togo'],
                        ['codigo' => 'TK', 'nombre' => 'Tokelau'],
                        ['codigo' => 'TO', 'nombre' => 'Tonga'],
                        ['codigo' => 'TT', 'nombre' => 'Trinidad and Tobago'],
                        ['codigo' => 'TN', 'nombre' => 'Tunisia'],
                        ['codigo' => 'TR', 'nombre' => 'Turkey'],
                        ['codigo' => 'TM', 'nombre' => 'Turkmenistan'],
                        ['codigo' => 'TC', 'nombre' => 'Turks and Caicos Islands'],
                        ['codigo' => 'TV', 'nombre' => 'Tuvalu'],
                        ['codigo' => 'UG', 'nombre' => 'Uganda'],
                        ['codigo' => 'UA', 'nombre' => 'Ukraine'],
                        ['codigo' => 'AE', 'nombre' => 'United Arab Emirates'],
                        ['codigo' => 'GB', 'nombre' => 'United Kingdom'],
                        ['codigo' => 'UM', 'nombre' => 'United States minor outlying islands'],
                        ['codigo' => 'UY', 'nombre' => 'Uruguay'],
                        ['codigo' => 'UZ', 'nombre' => 'Uzbekistan'],
                        ['codigo' => 'VU', 'nombre' => 'Vanuatu'],
                        ['codigo' => 'VA', 'nombre' => 'Vatican City State'],
                        ['codigo' => 'VE', 'nombre' => 'Venezuela'],
                        ['codigo' => 'VN', 'nombre' => 'Vietnam'],
                        ['codigo' => 'VG', 'nombre' => 'Virgin Islands (British)'],
                        ['codigo' => 'VI', 'nombre' => 'Virgin Islands (U.S.)'],
                        ['codigo' => 'WF', 'nombre' => 'Wallis and Futuna Islands'],
                        ['codigo' => 'EH', 'nombre' => 'Western Sahara'],
                        ['codigo' => 'YE', 'nombre' => 'Yemen'],
                        ['codigo' => 'YU', 'nombre' => 'Yugoslavia'],
                        ['codigo' => 'ZR', 'nombre' => 'Zaire'],
                        ['codigo' => 'ZM', 'nombre' => 'Zambia'],
                        ['codigo' => 'ZW', 'nombre' => 'Zimbabwe'],
                ];

                foreach ($paises as $pais) {
                        $this->db->query("INSERT INTO paises (codigo, nombre) VALUES(:codigo:, :nombre:)", $pais);
                }
        }
}